### ISSUE TITLE
Incorrect messaging when installing

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/pattoo#348]
The message gives the impression that running daemons will be stopped. This is not correct, they remain alive.

```
Inserting default database table entries.
Database setup complete.
Starting daemons

pattoo_apid daemon is already enabled/running, stopping daemon

pattoo_api_agentd daemon is already enabled/running, stopping daemon

pattoo_ingesterd daemon is already enabled/running, stopping daemon

```

**Comment by DangaRanga** [comment]
It does stop the daemons with the systemctl command if they're running and then runs them afterwards, to prevent the script from crashing if the daemons are already running. It just doesn't show that the command is being run when the verbose mode of the script is disabled, so it stops them silently.

 This is the code block that gets run in that segment.

`    # Check status code of daemon to see if its running
    status = shared.run_script(command, die=False, verbose=verbose)[0]
    if status == 0:
        print('''
{} daemon is already enabled/running, stopping daemon'''.format(daemon_name))

        # Stop daemon if its running
        shared.run_script('systemctl stop {}'.format(daemon_name),
                          verbose=verbose)
`
However, it occasionally doesn't remove the pid files if they are already there when they're stopped with systemctl, so that is something I'll have to add as apart of the systemd installation.

**Comment by palisadoes** [comment]
1. If running - restart - Message states restarting
2. If stopped - start - Message states starting
3. If fails to start or restart, then error message
